name: "Update: Trunk Upgrade"

on:
  schedule:
    - cron: 0 17 * * 1 # Every Monday at 5pm UTC
  workflow_dispatch:

permissions: read-all

jobs:
  trunk_upgrade:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Trunk Upgrade
        uses: trunk-io/trunk-action/upgrade@v1
        with:
          lowercase-title: true
          prefix: "test: "
